# Generated by Django 4.2.2 on 2024-02-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=10)),
                ('empname', models.CharField(max_length=40)),
                ('empdesignation', models.CharField(max_length=50)),
                ('empcontact', models.IntegerField()),
            ],
        ),
    ]
